name: Install Winget + dependencies
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - feature-Winget+Dependencies
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify PS versioning
        shell: pwsh
        run: pwsh --version

      - name: PS gallery source
        shell: pwsh
        run: Get-PackageSource

